### ISSUE TITLE
Failed to execute --command

### ISSUE THREAD

**Issue by ScreamingDev** [brot/gnome-shell-extension-sshsearch#11]
Got this error and do not know how to handle it:

![screenshot from 2013-10-31 17 45 38](https://f.cloud.github.com/assets/2559177/1447734/29e8587c-424c-11e3-90b6-1fd02a4b3c5f.png)

**Comment by ghost** [comment]
Hi,
I have same issue, I use Ubuntu 13.10 with Gnome-Shell 3.8.4. 

Look into file: ~/.local/share/gnome-shell/extensions/ssh-search-provider@gnome-shell-extensions.brot.github.com/extension.js 
- line 77
  Gio.Settings returns default terminal arg key ("-e")
- line 264
  Arg "-e" is not removed from arguments list
- line 270 
  argument --command is added
- line 285
  Script is trying to exec Util.spawn(gnome-terminal.wrapper, -e, --command, ssh [con-name]);

Sollution:
1. run gsettings and add schema for default terminal app (org.gnome.desktop.default-applications.terminal)
or:
2. comment out line 270: cmd.push('--command')
this works for my

Best,

**Comment by brot** [comment]
Thanks for your bug-report. There were a few other people reporting this bug and one guy helped me track down the issue (I didn't had much time the last few weeks)
Commited the fix for the 3.8 and 3.10 branch. I also uploaded the new versions to https://extensions.gnome.org.
Now we have to wait for the review. This could take a few days. But an update of the extension is on the way :-)
